### ISSUE TITLE
Compilation error in Train.java

### ISSUE THREAD

**Issue by KnowledgeGarden** [aika-algorithm/aika-wikipedia-model#1]
[ERROR] /c:/projects/AIKA/aika-wikipedia-model/src/main/java/org/aika/wikipedia/
Train.java:[86,93] incompatible types: boolean cannot be converted to org.aika.t
raining.SynapseEvaluation.DeleteMode

Not sure what that means.
Java 1.8.0_40
Win7 box.

**Comment by aika-algorithm** [comment]
Yes, that was a recent change to the aika repository. The DeleteMode specifies under which circumstances a synapse should be deleted again. It's a flag, that the training algorithm can set to automaticaly delete a synapse. It should now compile.
